apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_PROJECT_NAME-deployment
  namespace: $APP_KUBE_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_PROJECT_NAME
  replicas: $APP_REPLICAS
  template:
    metadata:
      labels:
        app: $APP_PROJECT_NAME
    spec:


      containers:
      - name: krakend
        image: $APP_IMAGE
        ports:
        - containerPort: 8080
        # imagePullPolicy: Never
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "krakend.json", "-p", "8080" ]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: KRAKEND_PORT
          value: "8080"