apiVersion: v1
kind: Service
metadata:
  name: $APP_PROJECT_NAME-loadbalancer
  namespace: $APP_KUBE_NAMESPACE
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: $APP_PROJECT_NAME
  ports:
    - protocol: TCP
      port: $APP_LOADBALANCER_PORT        # Puerto externo HTTPS
      targetPort: 8080 # Puerto del contenedor KrakenD
